import type { ActionConfig, FieldConfig, OperationConfig, ResourceConfig, Role } from './types';
import { cloudinaryImage } from '../customer/cloudinary';

type GenericRecord = Record<string, unknown>;

const statesActIna = [
  { label: 'Activo', value: 'ACT' },
  { label: 'Inactivo', value: 'INA' },
];

const statesUsuario = [
  { label: 'Activo', value: 'ACT' },
  { label: 'Inactivo', value: 'INA' },
  { label: 'Bloqueado', value: 'BLO' },
];

const tiposIdentificacion = [
  { label: 'Cedula', value: 'CED' },
  { label: 'RUC', value: 'RUC' },
  { label: 'Pasaporte', value: 'PAS' },
];

const tiposAlojamiento = [
  { label: 'Hotel', value: 'hotel' },
  { label: 'Hostal', value: 'hostal' },
  { label: 'Resort', value: 'resort' },
  { label: 'Departamento', value: 'departamento' },
  { label: 'Cabana', value: 'cabana' },
];

const categoriasViaje = [
  { label: 'Playa', value: 'playa' },
  { label: 'Ciudad', value: 'ciudad' },
  { label: 'Montana', value: 'montana' },
  { label: 'Aventura', value: 'aventura' },
  { label: 'Cultural', value: 'cultural' },
  { label: 'Bienestar', value: 'bienestar' },
];

const paises = [
  { label: 'Ecuador', value: 'Ecuador' },
  { label: 'Colombia', value: 'Colombia' },
  { label: 'Peru', value: 'Peru' },
  { label: 'Estados Unidos', value: 'Estados Unidos' },
  { label: 'Espana', value: 'Espana' },
];

const provinciasEcuador = [
  { label: 'Azuay', value: 'Azuay' },
  { label: 'Bolivar', value: 'Bolivar' },
  { label: 'Canar', value: 'Canar' },
  { label: 'Carchi', value: 'Carchi' },
  { label: 'Chimborazo', value: 'Chimborazo' },
  { label: 'Cotopaxi', value: 'Cotopaxi' },
  { label: 'El Oro', value: 'El Oro' },
  { label: 'Esmeraldas', value: 'Esmeraldas' },
  { label: 'Galapagos', value: 'Galapagos' },
  { label: 'Guayas', value: 'Guayas' },
  { label: 'Imbabura', value: 'Imbabura' },
  { label: 'Loja', value: 'Loja' },
  { label: 'Los Rios', value: 'Los Rios' },
  { label: 'Manabi', value: 'Manabi' },
  { label: 'Morona Santiago', value: 'Morona Santiago' },
  { label: 'Napo', value: 'Napo' },
  { label: 'Orellana', value: 'Orellana' },
  { label: 'Pastaza', value: 'Pastaza' },
  { label: 'Pichincha', value: 'Pichincha' },
  { label: 'Santa Elena', value: 'Santa Elena' },
  { label: 'Santo Domingo', value: 'Santo Domingo' },
  { label: 'Sucumbios', value: 'Sucumbios' },
  { label: 'Tungurahua', value: 'Tungurahua' },
  { label: 'Zamora Chinchipe', value: 'Zamora Chinchipe' },
];

const tiposCama = [
  { label: 'Individual', value: 'INDIVIDUAL' },
  { label: 'Doble', value: 'DOBLE' },
  { label: 'Queen', value: 'QUEEN' },
  { label: 'King', value: 'KING' },
  { label: 'Dos camas', value: 'DOS_CAMAS' },
  { label: 'Litera', value: 'LITERA' },
  { label: 'Sofa cama', value: 'SOFA_CAMA' },
];

const canalesReserva = [
  { label: 'Todos', value: 'TODOS' },
  { label: 'Backoffice', value: 'BACKOFFICE' },
  { label: 'Portal publico', value: 'PUBLICO' },
  { label: 'Recepcion', value: 'RECEPCION' },
  { label: 'Telefono', value: 'TELEFONO' },
  { label: 'Agencia', value: 'AGENCIA' },
  { label: 'Online travel agency', value: 'OTA' },
];

const tiposCatalogoServicio = [
  { label: 'Amenidad', value: 'AME' },
  { label: 'Servicio', value: 'SRV' },
];

const categoriasCatalogoServicio = [
  { label: 'Habitacion', value: 'HABITACION' },
  { label: 'Alimentos y bebidas', value: 'ALIMENTOS_BEBIDAS' },
  { label: 'Spa y bienestar', value: 'SPA' },
  { label: 'Transporte', value: 'TRANSPORTE' },
  { label: 'Lavanderia', value: 'LAVANDERIA' },
  { label: 'Eventos', value: 'EVENTOS' },
  { label: 'Otros', value: 'OTROS' },
];

const metodosPago = [
  { label: 'Efectivo', value: 'EFECTIVO' },
  { label: 'Tarjeta de credito', value: 'TARJETA_CREDITO' },
  { label: 'Tarjeta de debito', value: 'TARJETA_DEBITO' },
  { label: 'Transferencia', value: 'TRANSFERENCIA' },
  { label: 'Deposito', value: 'DEPOSITO' },
  { label: 'Pasarela', value: 'PASARELA' },
];

const proveedoresPasarela = [
  { label: 'Datafast', value: 'DATAFAST' },
  { label: 'PayPhone', value: 'PAYPHONE' },
  { label: 'Kushki', value: 'KUSHKI' },
  { label: 'PayPal', value: 'PAYPAL' },
  { label: 'Stripe', value: 'STRIPE' },
];

const monedas = [
  { label: 'USD', value: 'USD' },
  { label: 'EUR', value: 'EUR' },
];

const tiposViaje = [
  { label: 'Negocios', value: 'NEGOCIOS' },
  { label: 'Familiar', value: 'FAMILIAR' },
  { label: 'Pareja', value: 'PAREJA' },
  { label: 'Solo', value: 'SOLO' },
  { label: 'Amigos', value: 'AMIGOS' },
];

const boolField = (name: string, label: string, helpText?: string): FieldConfig => ({
  name,
  label,
  type: 'checkbox',
  helpText,
});

const reasonFields: FieldConfig[] = [
  {
    name: 'Motivo',
    label: 'Motivo',
    type: 'textarea',
    required: true,
    placeholder: 'Describe el motivo de la accion',
  },
];

const statusAction = (
  key: string,
  label: string,
  roles: Role[],
  endpoint: (record: GenericRecord) => string,
  options: { label: string; value: string }[],
): ActionConfig<GenericRecord> => ({
  key,
  label,
  roles,
  method: 'patch',
  endpoint,
  fields: [
    {
      name: 'Estado',
      label: 'Nuevo estado',
      type: 'select',
      required: true,
      options,
    },
  ],
  buildPayload: (values, _record, username) => ({
    Estado: values.Estado,
    Usuario: username,
  }),
  successMessage: `${label} ejecutado correctamente.`,
  variant: 'accent',
});

const withCreateAudit = (values: Record<string, unknown>, username: string, fieldName = 'CreadoPorUsuario') => ({
  ...sanitizePayload(values, 'create'),
  [fieldName]: username,
});

const withUpdateAudit = (values: Record<string, unknown>, username: string, fieldName = 'ModificadoPorUsuario') => ({
  ...sanitizePayload(values, 'update'),
  [fieldName]: username,
});

const mapTipoHabitacionPayload = (values: Record<string, unknown>, username: string, mode: 'create' | 'update') => ({
  CodigoTipoHabitacion: values.CodigoTipoHabitacion,
  NombreTipoHabitacion: values.NombreTipoHabitacion,
  Descripcion: values.Descripcion || null,
  CapacidadAdultos: values.CapacidadAdultos,
  CapacidadNinos: values.CapacidadNinos,
  CapacidadTotal: values.CapacidadTotal,
  TipoCama: values.TipoCama || null,
  AreaM2: values.AreaM2 === '' || values.AreaM2 === null || values.AreaM2 === undefined ? null : values.AreaM2,
  PermiteEventos: Boolean(values.PermiteEventos),
  PermiteReservaPublica: Boolean(values.PermiteReservaPublica),
  ...(mode === 'create'
    ? { CreadoPorUsuario: username }
    : {
        EstadoTipoHabitacion: values.EstadoTipoHabitacion,
        ModificadoPorUsuario: username,
      }),
});

function sanitizePayload(values: Record<string, unknown>, mode: 'create' | 'update') {
  const payload = { ...values };
  const keysToDrop = [
    'EsEliminado',
    'FechaRegistroUtc',
    'FechaModificacionUtc',
    'FechaInhabilitacionUtc',
    'MotivoInhabilitacion',
    'ModificacionIp',
    'ServicioOrigen',
    'RowVersion',
  ];

  for (const key of keysToDrop) {
    delete payload[key];
  }

  if (mode === 'create') {
    for (const key of Object.keys(payload)) {
      if (key.endsWith('Guid') || key.startsWith('Guid')) {
        delete payload[key];
      }
    }
  }

  return payload;
}

export const resourceConfigs: ResourceConfig<GenericRecord>[] = [
  {
    key: 'usuarios',
    title: 'Usuarios',
    description: 'Administracion de cuentas internas con acceso al sistema.',
    path: '/api/v1/internal/usuarios',
    idField: 'IdUsuario',
    roles: ['admin'],
    capabilities: { create: true, update: true, delete: true },
    columns: [
      { key: 'IdUsuario', label: 'ID' },
      { key: 'Username', label: 'Usuario' },
      { key: 'Correo', label: 'Correo' },
      { key: 'Nombres', label: 'Nombres' },
      { key: 'EstadoUsuario', label: 'Estado' },
      { key: 'Activo', label: 'Activo', render: (row) => ((row.Activo as boolean) ? 'Si' : 'No') },
    ],
    fields: [
      { name: 'Username', label: 'Usuario', type: 'text', required: true },
      { name: 'Correo', label: 'Correo', type: 'email', required: true },
      { name: 'Nombres', label: 'Nombres', type: 'text', required: true },
      { name: 'Apellidos', label: 'Apellidos', type: 'text' },
      { name: 'IdCliente', label: 'ID Cliente', type: 'number', min: 1 },
      { name: 'Password', label: 'Contrasena', type: 'text', required: true, createOnly: true },
      { name: 'EstadoUsuario', label: 'Estado', type: 'select', options: statesUsuario, required: true, updateOnly: true },
      boolField('Activo', 'Activo'),
    ],
    initialValues: {
      Username: '',
      Correo: '',
      Nombres: '',
      Apellidos: '',
      IdCliente: '',
      Password: '',
      EstadoUsuario: 'ACT',
      Activo: true,
    },
    prepareCreatePayload: (values, username) => withCreateAudit({ ...values, IdCliente: values.IdCliente || null }, username),
    prepareUpdatePayload: (values, username) => withUpdateAudit({ ...values, IdCliente: values.IdCliente || null }, username),
    actions: [
      {
        key: 'inhabilitar',
        label: 'Inhabilitar',
        roles: ['admin'],
        method: 'patch',
        endpoint: (row) => `/api/v1/internal/usuarios/${row.IdUsuario}/inhabilitar`,
        fields: reasonFields,
        buildPayload: (values, _record, username) => ({ Motivo: values.Motivo, Usuario: username }),
        successMessage: 'Usuario inhabilitado correctamente.',
        variant: 'danger',
      },
    ],
  },
  {
    key: 'roles',
    title: 'Roles',
    description: 'Definicion de perfiles de acceso administrativo.',
    path: '/api/v1/internal/roles',
    idField: 'IdRol',
    roles: ['admin'],
    capabilities: { create: true, update: true, delete: true },
    columns: [
      { key: 'IdRol', label: 'ID' },
      { key: 'NombreRol', label: 'Rol' },
      { key: 'DescripcionRol', label: 'Descripcion' },
      { key: 'EstadoRol', label: 'Estado' },
      { key: 'Activo', label: 'Activo', render: (row) => ((row.Activo as boolean) ? 'Si' : 'No') },
    ],
    fields: [
      { name: 'NombreRol', label: 'Nombre del rol', type: 'text', required: true },
      { name: 'DescripcionRol', label: 'Descripcion', type: 'textarea' },
      { name: 'EstadoRol', label: 'Estado', type: 'select', options: statesActIna, required: true },
      boolField('Activo', 'Activo'),
    ],
      initialValues: {
        NombreRol: '',
        DescripcionRol: '',
        EstadoRol: 'ACT',
        Activo: true,
      },
      prepareCreatePayload: (values, username) => withCreateAudit(values, username),
      prepareUpdatePayload: (values, username) => withUpdateAudit(values, username),
    },
  {
    key: 'clientes',
    title: 'Clientes',
    description: 'Base de clientes registrados del hotel.',
    path: '/api/v1/internal/clientes',
    idField: 'IdCliente',
    roles: ['admin', 'vendedor'],
    capabilities: { create: true, update: true, delete: true },
    columns: [
      { key: 'IdCliente', label: 'ID' },
      { key: 'Nombres', label: 'Nombres' },
      { key: 'Apellidos', label: 'Apellidos' },
      { key: 'Correo', label: 'Correo' },
      { key: 'Telefono', label: 'Telefono' },
      { key: 'Estado', label: 'Estado' },
    ],
    fields: [
      { name: 'TipoIdentificacion', label: 'Tipo identificacion', type: 'select', options: tiposIdentificacion, required: true },
      { name: 'NumeroIdentificacion', label: 'Numero identificacion', type: 'text', required: true },
      { name: 'Nombres', label: 'Nombres', type: 'text', required: true },
      { name: 'Apellidos', label: 'Apellidos', type: 'text' },
      { name: 'RazonSocial', label: 'Razon social', type: 'text' },
      { name: 'Correo', label: 'Correo', type: 'email', required: true },
      { name: 'Telefono', label: 'Telefono', type: 'text', required: true },
      { name: 'Direccion', label: 'Direccion', type: 'textarea', required: true },
      { name: 'Estado', label: 'Estado', type: 'select', options: statesActIna, required: true },
    ],
    initialValues: {
      TipoIdentificacion: 'CED',
      NumeroIdentificacion: '',
      Nombres: '',
      Apellidos: '',
      RazonSocial: '',
      Correo: '',
      Telefono: '',
      Direccion: '',
      Estado: 'ACT',
    },
    prepareCreatePayload: (values, username) => withCreateAudit(values, username),
    prepareUpdatePayload: (values, username) => withUpdateAudit(values, username),
  },
  {
    key: 'sucursales',
    title: 'Sucursales',
    description: 'Hoteles y propiedades publicadas en la plataforma.',
    path: '/api/v1/internal/sucursales',
    idField: 'IdSucursal',
    roles: ['admin', 'vendedor'],
    capabilities: { create: true, update: true, delete: true },
    columns: [
      { key: 'IdSucursal', label: 'ID' },
      { key: 'CodigoSucursal', label: 'Codigo' },
      { key: 'NombreSucursal', label: 'Sucursal' },
      { key: 'Ciudad', label: 'Ciudad' },
      { key: 'Pais', label: 'Pais' },
      { key: 'EstadoSucursal', label: 'Estado' },
    ],
    fields: [
      { name: 'CodigoSucursal', label: 'Codigo', type: 'text', required: true },
      { name: 'NombreSucursal', label: 'Nombre', type: 'text', required: true },
      { name: 'DescripcionSucursal', label: 'Descripcion completa', type: 'textarea' },
      { name: 'DescripcionCorta', label: 'Descripcion corta', type: 'textarea' },
      { name: 'TipoAlojamiento', label: 'Tipo alojamiento', type: 'select', options: tiposAlojamiento, required: true },
      { name: 'Estrellas', label: 'Estrellas', type: 'number', min: 0, max: 5 },
      { name: 'CategoriaViaje', label: 'Categoria viaje', type: 'select', options: categoriasViaje },
      { name: 'Pais', label: 'Pais', type: 'select', options: paises, required: true },
      { name: 'Provincia', label: 'Provincia', type: 'select', options: provinciasEcuador },
      { name: 'Ciudad', label: 'Ciudad', type: 'text', required: true },
      { name: 'Ubicacion', label: 'Ubicacion', type: 'text', required: true },
      { name: 'Direccion', label: 'Direccion', type: 'textarea', required: true },
      { name: 'CodigoPostal', label: 'Codigo postal', type: 'text' },
      { name: 'Telefono', label: 'Telefono', type: 'text', required: true },
      { name: 'Correo', label: 'Correo', type: 'email', required: true },
      { name: 'Latitud', label: 'Latitud', type: 'number', min: -90, max: 90, step: 0.000001 },
      { name: 'Longitud', label: 'Longitud', type: 'number', min: -180, max: 180, step: 0.000001 },
      { name: 'HoraCheckin', label: 'Hora check-in', type: 'time' },
      { name: 'HoraCheckout', label: 'Hora check-out', type: 'time' },
      boolField('CheckinAnticipado', 'Permite check-in anticipado'),
      boolField('CheckoutTardio', 'Permite check-out tardio'),
      boolField('AceptaNinos', 'Acepta ninos'),
      { name: 'EdadMinimaHuesped', label: 'Edad minima', type: 'number', min: 0, max: 120 },
      boolField('PermiteMascotas', 'Permite mascotas'),
      boolField('SePermiteFumar', 'Permite fumar'),
      { name: 'EstadoSucursal', label: 'Estado', type: 'select', options: statesActIna, required: true },
    ],
    initialValues: {
      CodigoSucursal: '',
      NombreSucursal: '',
      DescripcionSucursal: '',
      DescripcionCorta: '',
      TipoAlojamiento: 'hotel',
      Estrellas: 4,
      CategoriaViaje: '',
      Pais: 'Ecuador',
      Provincia: '',
      Ciudad: '',
      Ubicacion: '',
      Direccion: '',
      CodigoPostal: '',
      Telefono: '',
      Correo: '',
      Latitud: '',
      Longitud: '',
      HoraCheckin: '15:00',
      HoraCheckout: '12:00',
      CheckinAnticipado: false,
      CheckoutTardio: false,
      AceptaNinos: true,
      EdadMinimaHuesped: '',
      PermiteMascotas: false,
      SePermiteFumar: false,
      EstadoSucursal: 'ACT',
    },
    prepareCreatePayload: (values, username) => withCreateAudit(values, username),
    prepareUpdatePayload: (values, username) => withUpdateAudit(values, username),
  },
  {
    key: 'tipos-habitacion',
    title: 'Tipos de habitacion',
    description: 'Modelos de habitacion publicados por la operacion.',
    path: '/api/v1/internal/tipos-habitacion',
    idField: 'IdTipoHabitacion',
    updateIdField: 'TipoHabitacionGuid',
    roles: ['admin', 'vendedor'],
    capabilities: { create: true, update: true, delete: true },
    columns: [
      { key: 'IdTipoHabitacion', label: 'ID' },
      { key: 'CodigoTipoHabitacion', label: 'Codigo' },
      { key: 'NombreTipoHabitacion', label: 'Nombre' },
      { key: 'CapacidadTotal', label: 'Capacidad' },
      { key: 'TipoCama', label: 'Cama' },
      { key: 'EstadoTipoHabitacion', label: 'Estado' },
    ],
    fields: [
      { name: 'CodigoTipoHabitacion', label: 'Codigo', type: 'text', required: true },
      { name: 'NombreTipoHabitacion', label: 'Nombre', type: 'text', required: true },
      { name: 'Descripcion', label: 'Descripcion', type: 'textarea' },
      { name: 'CapacidadAdultos', label: 'Capacidad adultos', type: 'number', min: 1, required: true },
      { name: 'CapacidadNinos', label: 'Capacidad ninos', type: 'number', min: 0, required: true },
      { name: 'CapacidadTotal', label: 'Capacidad total', type: 'number', min: 1, required: true },
      { name: 'TipoCama', label: 'Tipo cama', type: 'select', options: tiposCama },
      { name: 'AreaM2', label: 'Area m2', type: 'number', min: 0, max: 10000, step: 0.01 },
      boolField('PermiteEventos', 'Permite eventos'),
      boolField('PermiteReservaPublica', 'Disponible en portal publico'),
      { name: 'EstadoTipoHabitacion', label: 'Estado', type: 'select', options: statesActIna, required: true, updateOnly: true },
    ],
    initialValues: {
      CodigoTipoHabitacion: '',
      NombreTipoHabitacion: '',
      Descripcion: '',
      CapacidadAdultos: 2,
      CapacidadNinos: 0,
      CapacidadTotal: 2,
      TipoCama: '',
      AreaM2: '',
      PermiteEventos: false,
      PermiteReservaPublica: true,
      EstadoTipoHabitacion: 'ACT',
    },
    prepareCreatePayload: (values, username) => mapTipoHabitacionPayload(values, username, 'create'),
    prepareUpdatePayload: (values, username) => mapTipoHabitacionPayload(values, username, 'update'),
  },
  {
    key: 'habitaciones',
    title: 'Habitaciones',
    description: 'Inventario fisico de habitaciones por sucursal.',
    path: '/api/v1/internal/habitaciones',
    idField: 'IdHabitacion',
    roles: ['admin', 'vendedor'],
    capabilities: { create: true, update: true, delete: true },
    columns: [
      { key: 'IdHabitacion', label: 'ID' },
      { key: 'NumeroHabitacion', label: 'Numero' },
      { key: 'IdSucursal', label: 'Sucursal' },
      { key: 'IdTipoHabitacion', label: 'Tipo' },
      { key: 'PrecioBase', label: 'Precio base' },
      { key: 'EstadoHabitacion', label: 'Estado' },
    ],
    fields: [
      { name: 'IdSucursal', label: 'ID Sucursal', type: 'number', required: true, min: 1 },
      { name: 'IdTipoHabitacion', label: 'ID Tipo habitacion', type: 'number', required: true, min: 1 },
      { name: 'NumeroHabitacion', label: 'Numero habitacion', type: 'text', required: true },
      { name: 'Piso', label: 'Piso', type: 'number' },
      { name: 'CapacidadHabitacion', label: 'Capacidad', type: 'number', required: true, min: 1, max: 20 },
      { name: 'PrecioBase', label: 'Precio base', type: 'number', required: true, min: 0.01, max: 100000, step: 0.01 },
      { name: 'DescripcionHabitacion', label: 'Descripcion', type: 'textarea' },
      {
        name: 'EstadoHabitacion',
        label: 'Estado',
        type: 'select',
        options: [
          { label: 'Disponible', value: 'DIS' },
          { label: 'Ocupada', value: 'OCU' },
          { label: 'Mantenimiento', value: 'MNT' },
          { label: 'Fuera de servicio', value: 'FDS' },
          { label: 'Inactiva', value: 'INA' },
        ],
        updateOnly: true,
      },
    ],
    initialValues: {
      IdSucursal: '',
      IdTipoHabitacion: '',
      NumeroHabitacion: '',
      Piso: '',
      CapacidadHabitacion: 2,
      PrecioBase: 1,
      DescripcionHabitacion: '',
      EstadoHabitacion: 'DIS',
    },
    prepareCreatePayload: (values, username) => withCreateAudit(values, username),
    prepareUpdatePayload: (values, username) => withUpdateAudit(values, username),
    actions: [
      statusAction(
        'estado-habitacion',
        'Cambiar estado',
        ['admin', 'vendedor'],
        (row) => `/api/v1/internal/habitaciones/${row.IdHabitacion}/estado`,
        [
          { label: 'Disponible', value: 'DIS' },
          { label: 'Ocupada', value: 'OCU' },
          { label: 'Mantenimiento', value: 'MNT' },
          { label: 'Fuera de servicio', value: 'FDS' },
          { label: 'Inactiva', value: 'INA' },
        ],
      ),
    ],
  },
  {
    key: 'tipos-habitacion-imagenes',
    title: 'Imagenes de habitacion',
    description: 'Galeria Cloudinary asociada a cada tipo de habitacion.',
    path: '/api/v1/internal/tipos-habitacion-imagenes',
    idField: 'IdTipoHabitacionImagen',
    roles: ['admin', 'vendedor'],
    capabilities: { create: true, update: true, delete: true },
    columns: [
      { key: 'IdTipoHabitacionImagen', label: 'ID' },
      { key: 'IdTipoHabitacion', label: 'Tipo' },
      {
        key: 'UrlImagen',
        label: 'Imagen',
        render: (row) => (
          <img
            src={cloudinaryImage(String(row.UrlImagen ?? ''), Number(row.IdTipoHabitacionImagen ?? 0), 180)}
            alt={String(row.DescripcionImagen ?? 'Imagen habitacion')}
            style={{ width: 96, height: 64, objectFit: 'cover', borderRadius: 8 }}
          />
        ),
      },
      { key: 'DescripcionImagen', label: 'Descripcion' },
      { key: 'OrdenVisualizacion', label: 'Orden' },
      { key: 'EsPrincipal', label: 'Principal', render: (row) => ((row.EsPrincipal as boolean) ? 'Si' : 'No') },
    ],
    fields: [
      { name: 'IdTipoHabitacion', label: 'ID Tipo habitacion', type: 'number', required: true, min: 1 },
      {
        name: 'UrlImagen',
        label: 'Public ID o URL Cloudinary',
        type: 'text',
        required: true,
        maxLength: 500,
        helpText: 'Ejemplo recomendado: gsaxbnwvncx5svjz2oor. Tambien acepta la URL completa de Cloudinary.',
      },
      { name: 'DescripcionImagen', label: 'Descripcion', type: 'text', maxLength: 255 },
      { name: 'OrdenVisualizacion', label: 'Orden', type: 'number', required: true, min: 1 },
      boolField('EsPrincipal', 'Imagen principal'),
    ],
    initialValues: {
      IdTipoHabitacion: '',
      UrlImagen: '',
      DescripcionImagen: '',
      OrdenVisualizacion: 1,
      EsPrincipal: true,
    },
    prepareCreatePayload: (values, username) => withCreateAudit(values, username),
    prepareUpdatePayload: (values) => sanitizePayload(values, 'update'),
  },
  {
    key: 'tarifas',
    title: 'Tarifas',
    description: 'Reglas comerciales y precios por tipo de habitacion.',
    path: '/api/v1/internal/tarifas',
    idField: 'IdTarifa',
    roles: ['admin', 'vendedor'],
    capabilities: { create: true, update: true, delete: true },
    columns: [
      { key: 'IdTarifa', label: 'ID' },
      { key: 'CodigoTarifa', label: 'Codigo' },
      { key: 'NombreTarifa', label: 'Nombre' },
      { key: 'PrecioPorNoche', label: 'Precio' },
      { key: 'CanalTarifa', label: 'Canal' },
      { key: 'EstadoTarifa', label: 'Estado' },
    ],
    fields: [
      { name: 'CodigoTarifa', label: 'Codigo', type: 'text', required: true },
      { name: 'IdSucursal', label: 'ID Sucursal', type: 'number', required: true, min: 1 },
      { name: 'IdTipoHabitacion', label: 'ID Tipo habitacion', type: 'number', required: true, min: 1 },
      { name: 'NombreTarifa', label: 'Nombre', type: 'text', required: true },
      { name: 'CanalTarifa', label: 'Canal', type: 'select', options: canalesReserva, required: true },
      { name: 'FechaInicio', label: 'Fecha inicio', type: 'date', required: true },
      { name: 'FechaFin', label: 'Fecha fin', type: 'date', required: true },
      { name: 'PrecioPorNoche', label: 'Precio por noche', type: 'number', required: true, min: 0.01, max: 100000, step: 0.01 },
      { name: 'PorcentajeIva', label: '% IVA', type: 'number', required: true, min: 0, max: 100, step: 0.01 },
      { name: 'MinNoches', label: 'Min noches', type: 'number', required: true, min: 1 },
      { name: 'MaxNoches', label: 'Max noches', type: 'number', min: 1 },
      boolField('PermitePortalPublico', 'Visible en portal publico'),
      { name: 'Prioridad', label: 'Prioridad', type: 'number', required: true, min: 1 },
      { name: 'EstadoTarifa', label: 'Estado', type: 'select', options: statesActIna, required: true },
    ],
    initialValues: {
      CodigoTarifa: '',
      IdSucursal: '',
      IdTipoHabitacion: '',
      NombreTarifa: '',
      CanalTarifa: 'TODOS',
      FechaInicio: '',
      FechaFin: '',
      PrecioPorNoche: 1,
      PorcentajeIva: 15,
      MinNoches: 1,
      MaxNoches: '',
      PermitePortalPublico: true,
      Prioridad: 1,
      EstadoTarifa: 'ACT',
    },
    prepareCreatePayload: (values, username) => withCreateAudit(values, username),
    prepareUpdatePayload: (values, username) => withUpdateAudit(values, username),
    actions: [
      {
        key: 'desactivar',
        label: 'Desactivar',
        roles: ['admin'],
        method: 'patch',
        endpoint: (row) => `/api/v1/internal/tarifas/${row.IdTarifa}/desactivar`,
        fields: reasonFields,
        buildPayload: (values, _record, username) => ({ Motivo: values.Motivo, Usuario: username }),
        successMessage: 'Tarifa desactivada correctamente.',
        variant: 'danger',
      },
    ],
  },
  {
    key: 'catalogo-servicios',
    title: 'Catalogo de servicios',
    description: 'Amenities, extras y servicios disponibles por propiedad.',
    path: '/api/v1/internal/catalogo-servicios',
    idField: 'IdCatalogo',
    roles: ['admin', 'vendedor'],
    capabilities: { create: true, update: true, delete: true },
    columns: [
      { key: 'IdCatalogo', label: 'ID' },
      { key: 'CodigoCatalogo', label: 'Codigo' },
      { key: 'NombreCatalogo', label: 'Nombre' },
      { key: 'TipoCatalogo', label: 'Tipo' },
      { key: 'PrecioBase', label: 'Precio' },
      { key: 'EstadoCatalogo', label: 'Estado' },
    ],
    fields: [
      { name: 'IdSucursal', label: 'ID Sucursal', type: 'number', min: 1 },
      { name: 'CodigoCatalogo', label: 'Codigo', type: 'text', required: true },
      { name: 'NombreCatalogo', label: 'Nombre', type: 'text', required: true },
      { name: 'TipoCatalogo', label: 'Tipo', type: 'select', options: tiposCatalogoServicio, required: true },
      { name: 'CategoriaCatalogo', label: 'Categoria', type: 'select', options: categoriasCatalogoServicio, required: true },
      { name: 'DescripcionCatalogo', label: 'Descripcion', type: 'textarea' },
      { name: 'PrecioBase', label: 'Precio base', type: 'number', min: 0, step: 0.01, required: true },
      boolField('AplicaIva', 'Aplica IVA'),
      boolField('Disponible24h', 'Disponible 24h'),
      { name: 'HoraInicio', label: 'Hora inicio', type: 'time' },
      { name: 'HoraFin', label: 'Hora fin', type: 'time' },
      { name: 'IconoUrl', label: 'Icono URL', type: 'text' },
      { name: 'EstadoCatalogo', label: 'Estado', type: 'select', options: statesActIna, required: true },
    ],
    initialValues: {
      IdSucursal: '',
      CodigoCatalogo: '',
      NombreCatalogo: '',
      TipoCatalogo: '',
      CategoriaCatalogo: '',
      DescripcionCatalogo: '',
      PrecioBase: 0,
      AplicaIva: false,
      Disponible24h: false,
      HoraInicio: '',
      HoraFin: '',
      IconoUrl: '',
      EstadoCatalogo: 'ACT',
    },
    prepareCreatePayload: (values, username) => withCreateAudit({ ...values, IdSucursal: values.IdSucursal || null }, username),
    prepareUpdatePayload: (values, username) => withUpdateAudit({ ...values, IdSucursal: values.IdSucursal || null }, username),
  },
  {
    key: 'reservas',
    title: 'Reservas',
    description: 'Operacion diaria de reservas internas y sus importes.',
    path: '/api/v1/internal/reservas',
    idField: 'IdReserva',
    roles: ['admin', 'vendedor'],
    capabilities: { create: true, update: true, delete: false },
    columns: [
      { key: 'IdReserva', label: 'ID' },
      { key: 'CodigoReserva', label: 'Codigo' },
      { key: 'IdCliente', label: 'Cliente' },
      { key: 'IdSucursal', label: 'Sucursal' },
      { key: 'FechaInicio', label: 'Inicio' },
      { key: 'FechaFin', label: 'Fin' },
      { key: 'EstadoReserva', label: 'Estado' },
    ],
    fields: [
      { name: 'CodigoReserva', label: 'Codigo reserva', type: 'text', required: true },
      { name: 'IdCliente', label: 'ID Cliente', type: 'number', required: true, min: 1 },
      { name: 'IdSucursal', label: 'ID Sucursal', type: 'number', required: true, min: 1 },
      { name: 'FechaReservaUtc', label: 'Fecha reserva UTC', type: 'datetime-local', required: true },
      { name: 'FechaInicio', label: 'Fecha inicio', type: 'datetime-local', required: true },
      { name: 'FechaFin', label: 'Fecha fin', type: 'datetime-local', required: true },
      { name: 'SubtotalReserva', label: 'Subtotal', type: 'number', min: 0, step: 0.01, required: true },
      { name: 'ValorIva', label: 'IVA', type: 'number', min: 0, step: 0.01, required: true },
      { name: 'TotalReserva', label: 'Total', type: 'number', min: 0, step: 0.01, required: true },
      { name: 'DescuentoAplicado', label: 'Descuento', type: 'number', min: 0, step: 0.01, required: true },
      { name: 'SaldoPendiente', label: 'Saldo pendiente', type: 'number', min: 0, step: 0.01, required: true },
      { name: 'OrigenCanalReserva', label: 'Canal', type: 'select', options: canalesReserva, required: true },
      {
        name: 'EstadoReserva',
        label: 'Estado',
        type: 'select',
        options: [
          { label: 'Pendiente', value: 'PEN' },
          { label: 'Confirmada', value: 'CON' },
          { label: 'Cancelada', value: 'CAN' },
          { label: 'Finalizada', value: 'FIN' },
        ],
        required: true,
      },
      { name: 'Observaciones', label: 'Observaciones', type: 'textarea' },
      boolField('EsWalkin', 'Es walk-in'),
      {
        name: 'Habitaciones',
        label: 'Habitaciones JSON',
        type: 'json',
        createOnly: true,
        required: true,
        helpText: 'Arreglo con IdHabitacion, IdTarifa, FechaInicio, FechaFin, NumAdultos, NumNinos, PrecioNocheAplicado, SubtotalLinea, ValorIvaLinea, DescuentoLinea y TotalLinea.',
      },
    ],
    initialValues: {
      CodigoReserva: '',
      IdCliente: '',
      IdSucursal: '',
      FechaReservaUtc: '',
      FechaInicio: '',
      FechaFin: '',
      SubtotalReserva: 0,
      ValorIva: 0,
      TotalReserva: 0,
      DescuentoAplicado: 0,
      SaldoPendiente: 0,
      OrigenCanalReserva: 'BACKOFFICE',
      EstadoReserva: 'PEN',
      Observaciones: '',
      EsWalkin: false,
      Habitaciones: '[]',
    },
    prepareCreatePayload: (values, username) => withCreateAudit(values, username),
    prepareUpdatePayload: (values, username) => withUpdateAudit(values, username),
    actions: [
      {
        key: 'confirmar',
        label: 'Confirmar',
        roles: ['admin', 'vendedor'],
        method: 'patch',
        endpoint: (row) => `/api/v1/internal/reservas/${row.IdReserva}/confirmar`,
        buildPayload: (_values, _record, username) => ({ Usuario: username }),
        successMessage: 'Reserva confirmada correctamente.',
        variant: 'accent',
      },
      {
        key: 'cancelar',
        label: 'Cancelar',
        roles: ['admin'],
        method: 'patch',
        endpoint: (row) => `/api/v1/internal/reservas/${row.IdReserva}/cancelar`,
        fields: reasonFields,
        buildPayload: (values, _record, username) => ({ Motivo: values.Motivo, Usuario: username }),
        successMessage: 'Reserva cancelada correctamente.',
        variant: 'danger',
      },
    ],
  },
  {
    key: 'estadias',
    title: 'Estadias',
    description: 'Seguimiento operativo de check-in y check-out.',
    path: '/api/v1/internal/estadias',
    idField: 'IdEstadia',
    roles: ['admin', 'vendedor'],
    capabilities: { create: false, update: false, delete: false },
    columns: [
      { key: 'IdEstadia', label: 'ID' },
      { key: 'IdReservaHabitacion', label: 'Reserva hab.' },
      { key: 'IdCliente', label: 'Cliente' },
      { key: 'IdHabitacion', label: 'Habitacion' },
      { key: 'EstadoEstadia', label: 'Estado' },
      { key: 'RequiereMantenimiento', label: 'Mant.', render: (row) => ((row.RequiereMantenimiento as boolean) ? 'Si' : 'No') },
    ],
    fields: [],
    initialValues: {},
    actions: [
      {
        key: 'checkout',
        label: 'Checkout',
        roles: ['admin', 'vendedor'],
        method: 'patch',
        endpoint: (row) => `/api/v1/internal/estadias/${row.IdEstadia}/checkout`,
        fields: [
          { name: 'ObservacionesCheckout', label: 'Observaciones', type: 'textarea' },
          boolField('RequiereMantenimiento', 'Enviar a mantenimiento'),
        ],
        buildPayload: (values, _record, username) => ({
          Usuario: username,
          ObservacionesCheckout: values.ObservacionesCheckout,
          RequiereMantenimiento: values.RequiereMantenimiento ?? false,
        }),
        successMessage: 'Checkout registrado correctamente.',
        variant: 'accent',
      },
    ],
  },
  {
    key: 'pagos',
    title: 'Pagos',
    description: 'Registro de cobros y conciliacion por factura.',
    path: '/api/v1/internal/pagos',
    idField: 'IdPago',
    roles: ['admin', 'vendedor'],
    capabilities: { create: true, update: false, delete: false },
    columns: [
      { key: 'IdPago', label: 'ID' },
      { key: 'IdFactura', label: 'Factura' },
      { key: 'IdReserva', label: 'Reserva' },
      { key: 'Monto', label: 'Monto' },
      { key: 'MetodoPago', label: 'Metodo' },
      { key: 'EstadoPago', label: 'Estado' },
    ],
    fields: [
      { name: 'IdFactura', label: 'ID Factura', type: 'number', required: true, min: 1 },
      { name: 'IdReserva', label: 'ID Reserva', type: 'number', required: true, min: 1 },
      { name: 'Monto', label: 'Monto', type: 'number', required: true, min: 0.01, step: 0.01 },
      { name: 'MetodoPago', label: 'Metodo', type: 'select', options: metodosPago, required: true },
      boolField('EsPagoElectronico', 'Pago electronico'),
      { name: 'ProveedorPasarela', label: 'Proveedor pasarela', type: 'select', options: proveedoresPasarela },
      { name: 'TransaccionExterna', label: 'Transaccion externa', type: 'text' },
      { name: 'CodigoAutorizacion', label: 'Codigo autorizacion', type: 'text' },
      { name: 'Referencia', label: 'Referencia', type: 'text' },
      {
        name: 'EstadoPago',
        label: 'Estado',
        type: 'select',
        required: true,
        options: [
          { label: 'Pendiente', value: 'PEN' },
          { label: 'Procesando', value: 'PRO' },
          { label: 'Aprobado', value: 'APR' },
          { label: 'Rechazado', value: 'REC' },
          { label: 'Cancelado', value: 'CAN' },
        ],
      },
      { name: 'FechaPagoUtc', label: 'Fecha pago', type: 'datetime-local', required: true },
      { name: 'Moneda', label: 'Moneda', type: 'select', options: monedas, required: true },
      { name: 'TipoCambio', label: 'Tipo cambio', type: 'number', required: true, min: 0.0001, step: 0.0001 },
    ],
    initialValues: {
      IdFactura: '',
      IdReserva: '',
      Monto: 1,
      MetodoPago: '',
      EsPagoElectronico: false,
      ProveedorPasarela: '',
      TransaccionExterna: '',
      CodigoAutorizacion: '',
      Referencia: '',
      EstadoPago: 'PEN',
      FechaPagoUtc: '',
      Moneda: 'USD',
      TipoCambio: 1,
    },
    actions: [
      statusAction(
        'estado-pago',
        'Cambiar estado',
        ['admin', 'vendedor'],
        (row) => `/api/v1/internal/pagos/${row.IdPago}/estado`,
        [
          { label: 'Procesando', value: 'PRO' },
          { label: 'Aprobado', value: 'APR' },
          { label: 'Rechazado', value: 'REC' },
          { label: 'Cancelado', value: 'CAN' },
        ],
      ),
    ],
  },
  {
    key: 'facturas',
    title: 'Facturas',
    description: 'Consulta de documentos tributarios emitidos.',
    path: '/api/v1/internal/facturas',
    idField: 'IdFactura',
    roles: ['admin', 'vendedor'],
    capabilities: { create: false, update: false, delete: false },
    columns: [
      { key: 'IdFactura', label: 'ID' },
      { key: 'NumeroFactura', label: 'Numero' },
      { key: 'IdCliente', label: 'Cliente' },
      { key: 'IdReserva', label: 'Reserva' },
      { key: 'Total', label: 'Total' },
      { key: 'Estado', label: 'Estado' },
    ],
    fields: [],
    initialValues: {},
    actions: [
      {
        key: 'anular-factura',
        label: 'Anular',
        roles: ['admin'],
        method: 'patch',
        endpoint: (row) => `/api/v1/internal/facturas/${row.IdFactura}/anular`,
        fields: reasonFields,
        buildPayload: (values, _record, username) => ({ Motivo: values.Motivo, Usuario: username }),
        successMessage: 'Factura anulada correctamente.',
        variant: 'danger',
      },
    ],
  },
  {
    key: 'valoraciones',
    title: 'Valoraciones',
    description: 'Moderacion de comentarios y respuesta del hotel.',
    path: '/api/v1/internal/valoraciones',
    idField: 'IdValoracion',
    roles: ['admin', 'vendedor'],
    capabilities: { create: true, update: false, delete: true },
    columns: [
      { key: 'IdValoracion', label: 'ID' },
      { key: 'IdCliente', label: 'Cliente' },
      { key: 'IdSucursal', label: 'Sucursal' },
      { key: 'PuntuacionGeneral', label: 'Punt.' },
      { key: 'EstadoValoracion', label: 'Estado' },
      { key: 'PublicadaEnPortal', label: 'Portal', render: (row) => ((row.PublicadaEnPortal as boolean) ? 'Si' : 'No') },
    ],
    fields: [
      { name: 'IdEstadia', label: 'ID Estadia', type: 'number', required: true, min: 1 },
      { name: 'IdCliente', label: 'ID Cliente', type: 'number', required: true, min: 1 },
      { name: 'IdSucursal', label: 'ID Sucursal', type: 'number', required: true, min: 1 },
      { name: 'IdHabitacion', label: 'ID Habitacion', type: 'number', min: 1 },
      { name: 'PuntuacionGeneral', label: 'Puntuacion general', type: 'number', required: true, min: 1, max: 10, step: 0.1 },
      { name: 'PuntuacionLimpieza', label: 'Limpieza', type: 'number', min: 1, max: 10, step: 0.1 },
      { name: 'PuntuacionConfort', label: 'Confort', type: 'number', min: 1, max: 10, step: 0.1 },
      { name: 'PuntuacionUbicacion', label: 'Ubicacion', type: 'number', min: 1, max: 10, step: 0.1 },
      { name: 'PuntuacionInstalaciones', label: 'Instalaciones', type: 'number', min: 1, max: 10, step: 0.1 },
      { name: 'PuntuacionPersonal', label: 'Personal', type: 'number', min: 1, max: 10, step: 0.1 },
      { name: 'PuntuacionCalidadPrecio', label: 'Calidad precio', type: 'number', min: 1, max: 10, step: 0.1 },
      { name: 'ComentarioPositivo', label: 'Comentario positivo', type: 'textarea' },
      { name: 'ComentarioNegativo', label: 'Comentario negativo', type: 'textarea' },
      { name: 'TipoViaje', label: 'Tipo viaje', type: 'select', options: tiposViaje },
      {
        name: 'EstadoValoracion',
        label: 'Estado',
        type: 'select',
        options: [
          { label: 'Pendiente', value: 'PEN' },
          { label: 'Publicada', value: 'PUB' },
          { label: 'Oculta', value: 'OCU' },
          { label: 'Respondida', value: 'REP' },
        ],
        required: true,
      },
      boolField('PublicadaEnPortal', 'Publicada en portal'),
      { name: 'RespuestaHotel', label: 'Respuesta hotel', type: 'textarea' },
    ],
    initialValues: {
      IdEstadia: '',
      IdCliente: '',
      IdSucursal: '',
      IdHabitacion: '',
      PuntuacionGeneral: 8,
      PuntuacionLimpieza: '',
      PuntuacionConfort: '',
      PuntuacionUbicacion: '',
      PuntuacionInstalaciones: '',
      PuntuacionPersonal: '',
      PuntuacionCalidadPrecio: '',
      ComentarioPositivo: '',
      ComentarioNegativo: '',
      TipoViaje: '',
      EstadoValoracion: 'PEN',
      PublicadaEnPortal: false,
      RespuestaHotel: '',
    },
    actions: [
      {
        key: 'moderar-valoracion',
        label: 'Moderar',
        roles: ['admin', 'vendedor'],
        method: 'patch',
        endpoint: (row) => `/api/v1/internal/valoraciones/${row.IdValoracion}/moderar`,
        fields: [
          {
            name: 'Estado',
            label: 'Nuevo estado',
            type: 'select',
            required: true,
            options: [
              { label: 'Publicar', value: 'PUB' },
              { label: 'Ocultar', value: 'OCU' },
              { label: 'Respondida', value: 'REP' },
            ],
          },
          {
            name: 'PublicadaEnPortal',
            label: 'Mostrar en pagina publica',
            type: 'select',
            required: true,
            options: [
              { label: 'Si, mostrarla en el home', value: 'true' },
              { label: 'No, mantenerla privada', value: 'false' },
            ],
          },
        ],
        buildPayload: (values, _record, username) => ({
          Estado: values.Estado,
          PublicadaEnPortal: String(values.PublicadaEnPortal) === 'true',
          Usuario: username,
        }),
        successMessage: 'Valoracion moderada correctamente.',
        variant: 'accent',
      },
      {
        key: 'responder-valoracion',
        label: 'Responder',
        roles: ['admin', 'vendedor'],
        method: 'patch',
        endpoint: (row) => `/api/v1/internal/valoraciones/${row.IdValoracion}/responder`,
        fields: [
          {
            name: 'Respuesta',
            label: 'Respuesta del hotel',
            type: 'textarea',
            required: true,
          },
        ],
        buildPayload: (values, _record, username) => ({ Respuesta: values.Respuesta, Usuario: username }),
        successMessage: 'Respuesta enviada correctamente.',
        variant: 'accent',
      },
    ],
  },
];

export const operationsConfig: OperationConfig[] = [
  {
    key: 'confirmar-reserva',
    title: 'Confirmar reserva',
    description: 'Confirma una reserva pendiente y genera su factura inicial.',
    method: 'patch',
    roles: ['admin', 'vendedor'],
    fields: [{ name: 'ReservaId', label: 'Reserva pendiente', type: 'number', required: true, min: 1 }],
    path: (values) => `/api/v1/internal/reservas/${values.ReservaId}/confirmar`,
    buildPayload: (_values, username) => ({ Usuario: username }),
    successMessage: 'Reserva confirmada correctamente.',
  },
  {
    key: 'checkin',
    title: 'Check-in de reserva',
    description: 'Convierte una reserva confirmada en estadia activa.',
    method: 'post',
    roles: ['admin', 'vendedor'],
    fields: [
      { name: 'ReservaId', label: 'ID Reserva', type: 'number', required: true, min: 1 },
      { name: 'ObservacionesCheckin', label: 'Observaciones', type: 'textarea' },
    ],
    path: (values) => `/api/v1/internal/estadias/checkin/${values.ReservaId}`,
    buildPayload: (values, username) => ({
      Usuario: username,
      ObservacionesCheckin: values.ObservacionesCheckin,
    }),
    successMessage: 'Check-in ejecutado correctamente.',
  },
  {
    key: 'factura-reserva',
    title: 'Generar factura de reserva',
    description: 'Emite la factura inicial asociada a una reserva.',
    method: 'post',
    roles: ['admin', 'vendedor'],
    fields: [{ name: 'ReservaId', label: 'Reserva confirmada', type: 'number', required: true, min: 1 }],
    path: (values) => `/api/v1/internal/facturas/generar-reserva/${values.ReservaId}`,
    buildPayload: (_values, username) => ({ Usuario: username }),
    successMessage: 'Factura de reserva generada correctamente.',
  },
  {
    key: 'factura-final',
    title: 'Generar factura final',
    description: 'Emite la factura final al cierre de la reserva.',
    method: 'post',
    roles: ['admin', 'vendedor'],
    fields: [{ name: 'ReservaId', label: 'Reserva', type: 'number', required: true, min: 1 }],
    path: (values) => `/api/v1/internal/facturas/generar-final/${values.ReservaId}`,
    buildPayload: (_values, username) => ({ Usuario: username }),
    successMessage: 'Factura final generada correctamente.',
  },
  {
    key: 'ver-cargos',
    title: 'Consultar cargos de estadia',
    description: 'Consulta cargos registrados sobre una estadia.',
    method: 'get',
    roles: ['admin', 'vendedor'],
    fields: [{ name: 'EstadiaId', label: 'ID Estadia', type: 'number', required: true, min: 1 }],
    path: (values) => `/api/v1/internal/estadias/${values.EstadiaId}/cargos`,
    successMessage: 'Consulta ejecutada.',
    responseMode: 'data',
  },
  {
    key: 'crear-cargo',
    title: 'Registrar cargo de estadia',
    description: 'Agrega consumos o cargos extras durante la estadia.',
    method: 'post',
    roles: ['admin', 'vendedor'],
    fields: [
      { name: 'EstadiaId', label: 'Estadia', type: 'number', required: true, min: 1 },
      { name: 'IdCatalogo', label: 'Servicio del catalogo', type: 'number', min: 1 },
      { name: 'DescripcionCargo', label: 'Descripcion', type: 'textarea', required: true },
      { name: 'Cantidad', label: 'Cantidad', type: 'number', required: true, min: 1 },
      { name: 'PrecioUnitario', label: 'Precio unitario', type: 'number', required: true, min: 0, step: 0.01 },
      { name: 'ValorIva', label: 'IVA', type: 'number', required: true, min: 0, step: 0.01 },
      { name: 'FechaConsumoUtc', label: 'Fecha consumo', type: 'datetime-local', required: true },
      {
        name: 'EstadoCargo',
        label: 'Estado cargo',
        type: 'select',
        required: true,
        options: [
          { label: 'Pendiente', value: 'PEN' },
          { label: 'Aprobado', value: 'APR' },
          { label: 'Anulado', value: 'ANU' },
        ],
      },
    ],
    path: (values) => `/api/v1/internal/estadias/${values.EstadiaId}/cargos`,
    buildPayload: (values, username) => ({
      IdCatalogo: values.IdCatalogo || null,
      DescripcionCargo: values.DescripcionCargo,
      Cantidad: values.Cantidad,
      PrecioUnitario: values.PrecioUnitario,
      ValorIva: values.ValorIva,
      FechaConsumoUtc: values.FechaConsumoUtc ? new Date(String(values.FechaConsumoUtc)).toISOString() : values.FechaConsumoUtc,
      EstadoCargo: values.EstadoCargo,
      CreadoPorUsuario: username,
    }),
    successMessage: 'Cargo registrado correctamente.',
  },
  {
    key: 'anular-cargo',
    title: 'Anular cargo',
    description: 'Revierte un cargo especifico de una estadia.',
    method: 'patch',
    roles: ['admin'],
    fields: [
      { name: 'EstadiaId', label: 'Estadia', type: 'number', min: 1 },
      { name: 'CargoId', label: 'Cargo', type: 'number', required: true, min: 1 },
    ],
    path: (values) => `/api/v1/internal/cargos-estadia/${values.CargoId}/anular`,
    successMessage: 'Cargo anulado correctamente.',
  },
];

export function getResourceConfig(key: string) {
  return resourceConfigs.find((resource) => resource.key === key);
}

export function getVisibleResources(roles: Role[]) {
  return resourceConfigs.filter((resource) => resource.roles.some((role) => roles.includes(role)));
}
